### ISSUE TITLE
DLL load failed while importing cv2: The specified procedure could not be found.

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/gVXR-Tutorials#8]
Created environment with instructions in README

On importing:

```python
from gvxrPython3.JSON2gVXRDataReader import *
```

which imports the TIFF reader from cil, we get error:

```
ImportError: DLL load failed while importing cv2: The specified procedure could not be found.
```

Also get the error on: `from cil.io import TIFFWriter`

**Comment by effepivi** [comment]
@lauramurgatroyd Please check what "edition" of Windows you're using. 
On the one hand, it is possible that a Windows component is missing.
[See here](https://pypi.org/project/opencv-python/#frequently-asked-questions).
On the other hand, I don't know why OpenCV is used. 
If I don't use the TIFFReader and TIFFWriter the problem goes as far as the demo is concerned, but the dependency should be fixed.

**Comment by lauramurgatroyd** [comment]
Hi, I am on Windows 11 (is that what you mean by edition?)

I installed with pip, and I can see it listed in my environment:
```
# Name                    Version                   Build  Channel
libopencv                 4.10.0          qt6_py311h5a8f696_608    conda-forge
py-opencv                 4.10.0          qt6_py311hd635bfb_608    conda-forge
```


However I still get the error:
ImportError: DLL load failed while importing cv2: The specified procedure could not be found.
